version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  server:
    build:
      dockerfile: 'Dockerfile.dev'
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_DB=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres_password
  client:
    build:
      dockerfile: 'Dockerfile.dev'
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: 'Dockerfile.dev'
      context: './worker'
    volumes:
      - /app/node_modules
      - ./worker:/app
